export const guideData = {
  dataUser: [
    {
      title: '¡ El primer paso en tu búsqueda de empleo !',
      text: 'Crea tu perfil profesional y sube tu CV a nuestra plataforma',
    },
    {
      text: 'Empieza a aplicar a las ofertas que se adaptan a lo que estás buscando. Puedes filtrar por empresa o puesto',
    },
    {
      text: '¡ Podrás ver el estado de tus candidaturas y el proceso en el que te encuentras dentro de cada empresa !',
    },
  ],
  dataCompany: [
    {
      title: '¡Encuentra aqui los mejores candidatos para tus ofertas!',
      text: 'Crea tus ofertas y deja que los candidatos se inscriban en ellas',
    },
    {
      text: 'Evalúa cada candidato, pudiendo ver su perfil o leer su CV',
    },
    {
      text: 'Si algún candidato cumple tus requisitos, habla con él directamente a través de nuestro chat',
    },
  ],
};

export const cities = [
  'Álava',
  'Ávila',
  'Albacete',
  'Alicante',
  'Almería',
  'Asturias',
  'Badajoz',
  'Baleares',
  'Barcelona',
  'Bilbao',
  'Burgos',
  'Cantabria',
  'Castellón',
  'Ceuta',
  'Ciudad Real',
  'Coruña',
  'Cuenca',
  'Cáceres',
  'Cádiz',
  'Córdoba',
  'Donostia',
  'Gerona',
  'Granada',
  'Huelva',
  'Huesca',
  'Jaén',
  'Las Palmas',
  'León',
  'Lleida',
  'Lugo',
  'Madrid',
  'Melilla',
  'Murcia',
  'Málaga',
  'Navarra',
  'Orense',
  'Palencia',
  'Pontevedra',
  'Rioja',
  'Salamanca',
  'Segovia',
  'Sevilla',
  'Soria',
  'Tarragona',
  'Tenerife',
  'Teruel',
  'Toledo',
  'Valencia',
  'Valladolid',
  'Zamora',
  'Zaragoza',
];

export const categories = [
  'Aeronaútica',
  'Agricultura',
  'Almacenamiento',
  'Animación',
  'Apuestas y casinos',
  'Arquitectura y planificación',
  'Artesanía',
  'Artes escénicas',
  'Banca',
  'Construccion',
  'Cosmética',
  'Deportes',
  'Derecho',
  'Desarrollo Web',
  'E-learning',
  'Entretenimiento',
  'Formación profesional y captación',
  'Ganadería',
  'Hostelería',
  'Industria textil y moda',
  'Informática',
  'Internet',
  'Judicial',
  'Medicina',
  'Marketing y publicidad',
  'Naval',
  'Recursos humanos',
  'Sanidad, bienestar y ejercicio',
  'Seguros',
  'Servicios financieros',
  'Telecomunicaciones',
  'Videojuegos',
];
